/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analizadorlexico0;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.FileReader;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bruni
 */
public class TablaSimbolo extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
DefaultTableModel modelo1 = new DefaultTableModel();
    /**
     * Creates new form TablaSimbolo
     */
    public TablaSimbolo() {
        initComponents();
        this.getContentPane().setBackground(Color.red);
        this.setTitle("TABLA DE SIMBOLOS");
        modelo.addColumn("Símbolo");
        modelo.addColumn("Componente léxico");
        modelo.addColumn("Lexema 1");
        modelo.addColumn("lexema 2");
    }

    public void enviar() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        t = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();
        btnGenerar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_simbolo = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnLexema = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLexema = new javax.swing.JTextArea();

        t.setColumns(20);
        t.setRows(5);
        jScrollPane4.setViewportView(t);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCodigo.setColumns(20);
        txtCodigo.setRows(5);
        jScrollPane1.setViewportView(txtCodigo);

        btnGenerar.setBackground(new java.awt.Color(255, 153, 153));
        btnGenerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarMouseClicked(evt);
            }
        });
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        tabla_simbolo.setBackground(new java.awt.Color(204, 255, 102));
        tabla_simbolo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabla_simbolo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_simbolo.setGridColor(new java.awt.Color(255, 255, 153));
        jScrollPane2.setViewportView(tabla_simbolo);

        btnBuscar.setBackground(new java.awt.Color(255, 153, 204));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar txt");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLexema.setBackground(new java.awt.Color(255, 153, 255));
        btnLexema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLexema.setText("LexemaCodigo");
        btnLexema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexemaActionPerformed(evt);
            }
        });

        txtLexema.setColumns(20);
        txtLexema.setRows(5);
        jScrollPane3.setViewportView(txtLexema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnBuscar))
                            .addComponent(btnLexema))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenerar)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLexema)
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed

        File archivo = new File("archivo.txt");
        PrintWriter escribir;
        try {
            escribir = new PrintWriter(archivo);
            escribir.print(txtCodigo.getText());
            escribir.close();
        } catch (FileNotFoundException ex) {

        }
        modelo.getDataVector().removeAllElements();
        tabla_simbolo.updateUI();

        try {
            Reader lector = new BufferedReader(new FileReader("archivo.txt"));
            metodos a = new metodos(lector);

            TOKEN token = null;
            do {
                token = a.nextToken();
                modelo.addRow(new Object[]{token.token, token.lexico, token.lexema1, token.lexema2});

            } while (token != null);
        } catch (Exception ex) {

        }
        tabla_simbolo.setModel(modelo);
        
        //TXT TABLA
    String celda= "";
    String guardar="";
    for(int i=0; i<tabla_simbolo.getRowCount();i++){
        celda=(String)tabla_simbolo.getValueAt(i, 0)+" "+(String)tabla_simbolo.getValueAt(i, 1)+" "+(String)tabla_simbolo.getValueAt(i, 2)+" "+(String)tabla_simbolo.getValueAt(i, 3);
        guardar+=celda+"\n";
        t.setText(guardar);
        File archivo1 = new File("Tabla.txt");
        PrintWriter escribir1;
        try {
            escribir1 = new PrintWriter(archivo1);
            escribir1.print(t.getText());
            escribir1.close();
        } catch (FileNotFoundException ex) {
        
    }
    }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
JFileChooser fc = new JFileChooser();
        
        int seleccion = fc.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION){
            File fichero = fc.getSelectedFile();
            this.txtCodigo.setText(fichero.getAbsolutePath());
            
            try(FileReader fr = new FileReader(fichero)){
                String cadena = "";
                int valor = fr.read();
                while(valor != -1){
                    cadena= cadena + (char) valor;
                    valor = fr.read();
                }
                this.txtCodigo.setText(cadena);
                
            }catch(IOException e1){
                e1.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLexemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexemaActionPerformed
    
    String celda= "";
    int posicion= 2;
    String guardar="";
    for(int i=0; i<tabla_simbolo.getRowCount();i++){
        celda=(String)tabla_simbolo.getValueAt(i, posicion);
        if(celda=="DEL" || celda=="LLI" ){
            guardar+=celda+"\n";
        }else{
        guardar+=celda+" ";
        txtLexema.setText(guardar);
        File archivo1 = new File("archivoLexema.txt");
        PrintWriter escribir1;
        try {
            escribir1 = new PrintWriter(archivo1);
            escribir1.print(txtLexema.getText());
            escribir1.close();
        } catch (FileNotFoundException ex) {
        }
    }
    }
    }//GEN-LAST:event_btnLexemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaSimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaSimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaSimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaSimbolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaSimbolo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnLexema;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea t;
    private javax.swing.JTable tabla_simbolo;
    private javax.swing.JTextArea txtCodigo;
    private javax.swing.JTextArea txtLexema;
    // End of variables declaration//GEN-END:variables
   
}
